'use client';
import {useState,useEffect,useRef,useCallback} from 'react';
import {Film,Upload,ArrowUpRight,Layers,Sparkles,MousePointer2,Type,Play,Pause,SkipBack,SkipForward,Plus,ZoomIn,Check,Scissors,Undo2,Redo2,Monitor,Volume2,VolumeX,Trash2,Download,FolderOpen,RotateCcw,Loader2} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import {initialProject,themes,uid,clamp,duration,sourceTime,size,formatTime,renderFrame,validateProject,type Project,type Zoom} from '@/lib/editor';
import {storeVideo,restoreVideo} from '@/lib/storage';

function Range({label,value,min=0,max=100,step=1,unit='',onChange}:{label:string;value:number;min?:number;max?:number;step?:number;unit?:string;onChange:(n:number)=>void}){return <div className="setting"><div><label>{label}</label><span>{Number(value.toFixed(2))}{unit}</span></div><Slider aria-label={label} value={[value]} min={min} max={max} step={step} onValueChange={v=>onChange(Array.isArray(v)?v[0]:v)}/></div>}
function Choice({label,value,options,onChange}:{label:string;value:string;options:[string,string][];onChange:(v:string)=>void}){return <Select value={value} onValueChange={v=>v&&onChange(v)}><SelectTrigger aria-label={label} className="choice"><SelectValue>{options.find(o=>o[0]===value)?.[1]}</SelectValue></SelectTrigger><SelectContent>{options.map(([v,l])=><SelectItem value={v} key={v}>{l}</SelectItem>)}</SelectContent></Select>}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}

export default function Home(){
 const [p,setP]=useState<Project>(initialProject),[tab,setTab]=useState('Canvas'),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[videoUrl,setVideoUrl]=useState(''),[fileName,setFileName]=useState('Orbit · Product walkthrough'),[selected,setSelected]=useState('z1'),[selectedClip,setSelectedClip]=useState('c1'),[notice,setNotice]=useState(''),[saveStatus,setSaveStatus]=useState('Saved on this device'),[ready,setReady]=useState(false),[exportOpen,setExportOpen]=useState(false),[exporting,setExporting]=useState(false),[progress,setProgress]=useState(0),[quality,setQuality]=useState('1080'),[history,setHistory]=useState<Project[]>([]),[future,setFuture]=useState<Project[]>([]),[dragging,setDragging]=useState(false),[loading,setLoading]=useState(false);
 const canvas=useRef<HTMLCanvasElement>(null),video=useRef<HTMLVideoElement>(null),fileInput=useRef<HTMLInputElement>(null),projectInput=useRef<HTMLInputElement>(null),live=useRef({p,time,playing}),cancel=useRef(false),audio=useRef<{context:AudioContext;source:MediaElementAudioSourceNode}|null>(null),sourceDuration=useRef(24),urlRef=useRef('');
 live.current={p,time,playing};const total=duration(p),zoom=p.zooms.find(z=>z.id===selected),caption=p.captions.find(c=>c.id===selected),clip=p.clips.find(c=>c.id===selectedClip);const [W,H]=size(p.ratio);
 const inform=useCallback((s:string)=>setNotice(s),[]);
 const update=useCallback((patch:Partial<Project>)=>{setP(old=>{setHistory(h=>[...h.slice(-49),old]);setFuture([]);return {...old,...patch};});},[]);
 const undo=()=>{if(!history.length)return;setFuture(f=>[p,...f]);setP(history.at(-1)!);setHistory(h=>h.slice(0,-1));setPlaying(false);};
 const redo=()=>{if(!future.length)return;setHistory(h=>[...h,p]);setP(future[0]);setFuture(f=>f.slice(1));setPlaying(false);};
 const seek=useCallback((t:number)=>{setTime(clamp(t,0,duration(live.current.p)));},[]);
 const addZoom=()=>{const at=Math.min(time,Math.max(0,total-1)),z={id:uid(),start:at,duration:Math.min(4,total-at),scale:1.6,x:.5,y:.5};update({zooms:[...p.zooms,z]});setSelected(z.id);setTab('Zoom');setPlaying(false);inform('Zoom added. Click the preview to set its focus.');};
 const editZoom=(patch:Partial<Zoom>)=>zoom&&update({zooms:p.zooms.map(z=>z.id===zoom.id?{...z,...patch}:z)});
 const addText=()=>{const at=Math.min(time,Math.max(0,total-1)),c={id:uid(),start:at,duration:Math.min(4,total-at),text:'Your next great idea, in motion.'};update({captions:[...p.captions,c]});setSelected(c.id);setTab('Text');};
 const split=()=>{let at=time*p.speed;const clips=[...p.clips];for(let i=0;i<clips.length;i++){const c=clips[i],len=c.end-c.start;if(at<len){if(at<.1||len-at<.1){inform('Move the playhead inside a clip to split it.');return;}const next={id:uid(),start:c.start+at,end:c.end};clips.splice(i,1,{...c,end:c.start+at},next);update({clips});setSelectedClip(next.id);setTab('Clip');inform('Clip split. Select either segment to trim or remove it.');return;}at-=len;}};
 const toggle=()=>{if(time>=total-.02)setTime(0);setPlaying(v=>!v);};
 useEffect(()=>{let stopped=false;const saved=localStorage.getItem('take-project-v1');if(saved){try{setP(validateProject(JSON.parse(saved)));}catch{inform('The previous project could not be restored. A sample is ready.');}}restoreVideo().then(file=>{if(stopped)return;if(file){const url=URL.createObjectURL(file);urlRef.current=url;setVideoUrl(url);setFileName(file.name);}setReady(true);}).catch(()=>{if(!stopped){setReady(true);setSaveStatus('Browser storage unavailable');}});return()=>{stopped=true;if(urlRef.current)URL.revokeObjectURL(urlRef.current);};},[inform]);
 useEffect(()=>{if(!ready)return;const id=setTimeout(()=>{try{localStorage.setItem('take-project-v1',JSON.stringify(p));setSaveStatus('Saved on this device');}catch{setSaveStatus('Save project to keep changes');}},400);return()=>clearTimeout(id);},[p,ready]);
 useEffect(()=>{if(notice){const id=setTimeout(()=>setNotice(''),5000);return()=>clearTimeout(id);}},[notice]);
 useEffect(()=>{setTime(t=>Math.min(t,total));},[total]);
 useEffect(()=>{const v=video.current;if(!v||!videoUrl)return;v.playbackRate=p.speed;v.muted=p.muted;if(playing&&!exporting){v.play().catch(()=>{setPlaying(false);inform('Playback could not start. Try pressing play again.');});}else if(!exporting)v.pause();},[playing,p.speed,p.muted,videoUrl,exporting,inform]);
 useEffect(()=>{if(exporting)return;let raf=0,last=performance.now();const tick=(now:number)=>{const state=live.current;let t=state.time;const v=video.current;if(state.playing){t=Math.min(duration(state.p),t+Math.min((now-last)/1000,.1));if(t>=duration(state.p)){setPlaying(false);v?.pause();}setTime(t);}last=now;if(v&&videoUrl){const target=sourceTime(state.p,t);if(Math.abs(v.currentTime-target)>(state.playing?.2:.025))v.currentTime=target;}if(canvas.current)renderFrame(canvas.current,state.p,t,videoUrl?v:null);raf=requestAnimationFrame(tick);};raf=requestAnimationFrame(tick);return()=>cancelAnimationFrame(raf);},[videoUrl,exporting]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(exporting||exportOpen||e.target instanceof HTMLInputElement||e.target instanceof HTMLTextAreaElement||(e.target as HTMLElement)?.closest('[role="dialog"],[role="combobox"],[role="slider"]'))return;if(e.code==='Space'){e.preventDefault();toggle();}if(e.key==='ArrowRight'){e.preventDefault();seek(time+1);}if(e.key==='ArrowLeft'){e.preventDefault();seek(time-1);}if((e.ctrlKey||e.metaKey)&&e.key==='z'){e.preventDefault();e.shiftKey?redo():undo();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 async function importFile(file?:File){if(!file)return;if(!file.type.startsWith('video/')&&!/\.(mp4|webm|mov|m4v)$/i.test(file.name)){inform('Choose an MP4, WebM, or MOV video.');return;}setLoading(true);setPlaying(false);const url=URL.createObjectURL(file),probe=document.createElement('video');probe.preload='metadata';probe.src=url;try{await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('The video took too long to load.')),15000);probe.onloadedmetadata=()=>{clearTimeout(timer);resolve();};probe.onerror=()=>{clearTimeout(timer);reject(new Error('This browser cannot decode that video. Try H.264 MP4.'));};});if(!Number.isFinite(probe.duration)||probe.duration<=0)throw new Error('The recording has no usable duration.');sourceDuration.current=probe.duration;URL.revokeObjectURL(urlRef.current);urlRef.current=url;setVideoUrl(url);setFileName(file.name);setP({...initialProject,name:file.name.replace(/\.[^.]+$/,''),zooms:[],captions:[],clips:[{id:uid(),start:0,end:probe.duration}]});setHistory([]);setFuture([]);setTime(0);setSelected('');setTab('Canvas');try{await storeVideo(file);inform('Video imported and saved on this device.');}catch{inform('Video imported. Browser storage is full; keep this tab open.');}}catch(e){URL.revokeObjectURL(url);inform((e as Error).message);}finally{probe.removeAttribute('src');probe.load();setLoading(false);}}
 async function exportVideo(){if(typeof MediaRecorder==='undefined'){inform('Video export is not supported in this browser. Try Chrome or Edge.');return;}const mime=['video/mp4;codecs=avc1.42001f,mp4a.40.2','video/mp4','video/webm;codecs=vp9,opus','video/webm'].find(m=>MediaRecorder.isTypeSupported(m));if(!mime){inform('No supported video encoder. Try Chrome or Edge.');return;}setPlaying(false);setExporting(true);setProgress(0);cancel.current=false;const out=document.createElement('canvas'),[ew,eh]=size(p.ratio,Number(quality));out.width=ew;out.height=eh;const stream=out.captureStream(30),v=video.current;let dest:MediaStreamAudioDestinationNode|undefined,raf=0;try{if(v&&videoUrl){v.pause();const start=sourceTime(p,0);if(Math.abs(v.currentTime-start)>.01){await new Promise<void>((res,rej)=>{const timer=setTimeout(()=>rej(new Error('Could not seek the source video.')),10000);v.addEventListener('seeked',()=>{clearTimeout(timer);res();},{once:true});v.currentTime=start;});}if(!p.muted){if(!audio.current){const context=new AudioContext();audio.current={context,source:context.createMediaElementSource(v)};audio.current.source.connect(context.destination);}await audio.current.context.resume();dest=audio.current.context.createMediaStreamDestination();audio.current.source.connect(dest);dest.stream.getAudioTracks().forEach(track=>stream.addTrack(track));}v.playbackRate=p.speed;v.muted=p.muted;}
 renderFrame(out,p,0,videoUrl?v:null);const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:8000000}),chunks:BlobPart[]=[];const done=new Promise<Blob>((resolve,reject)=>{recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};recorder.onstop=()=>resolve(new Blob(chunks,{type:mime}));recorder.onerror=()=>reject(new Error('The video encoder stopped unexpectedly.'));});recorder.start(250);if(v&&videoUrl)await v.play();let elapsed=0,previous=performance.now();await new Promise<void>(resolve=>{const frame=(now:number)=>{const dt=Math.min((now-previous)/1000,.1);previous=now;if(!(v&&videoUrl&&(v.seeking||v.readyState<2)))elapsed+=dt;const t=Math.min(total,elapsed);if(v&&videoUrl){const desired=sourceTime(p,t);if(Math.abs(v.currentTime-desired)>.3&&!v.seeking)v.currentTime=desired;}renderFrame(out,p,t,videoUrl?v:null);if(canvas.current)renderFrame(canvas.current,p,t,videoUrl?v:null);setProgress(Math.min(99,t/total*100));if(t>=total||cancel.current){resolve();return;}raf=requestAnimationFrame(frame);};raf=requestAnimationFrame(frame);});recorder.stop();const blob=await done;if(!cancel.current){download(blob,`${p.name||'Take demo'}.${mime.startsWith('video/mp4')?'mp4':'webm'}`);setProgress(100);inform('Your video is ready. Download started.');}}catch(e){inform(`Export failed: ${(e as Error).message}`);}finally{cancelAnimationFrame(raf);v?.pause();stream.getTracks().forEach(t=>t.stop());if(dest&&audio.current)audio.current.source.disconnect(dest);setExporting(false);setTime(0);}}
 async function openProject(file?:File){if(!file)return;try{const next=validateProject(JSON.parse(await file.text()));if(next.clips.some(c=>c.end>sourceDuration.current+.1))throw new Error('Import the matching source recording before opening this project.');setP(next);setHistory([]);setFuture([]);setTime(0);setPlaying(false);inform('Project opened.');}catch(e){inform((e as Error).message);}}
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>void}}).modelContext;if(!context?.registerTool)return;const controller=new AbortController();try{context.registerTool({name:'read_take_project',description:'Read the current demo edit and duration.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({project:live.current.p,duration:duration(live.current.p)})},{signal:controller.signal});context.registerTool({name:'set_take_background',description:'Set the current demo background preset.',inputSchema:{type:'object',properties:{theme:{type:'integer',minimum:0,maximum:5}},required:['theme'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const n=(input as {theme:number}).theme;if(!Number.isInteger(n)||n<0||n>5)throw new Error('Choose a theme from 0 through 5.');update({theme:n});await new Promise(requestAnimationFrame);return{theme:n,name:themes[n].name};}},{signal:controller.signal});}catch{console.warn('Optional WebMCP registration unavailable.');}return()=>controller.abort();},[update]);

 return <main className="studio" onDragOver={e=>{e.preventDefault();if(!exporting)setDragging(true);}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDragging(false);}} onDrop={e=>{e.preventDefault();setDragging(false);if(!exporting)void importFile(e.dataTransfer.files[0]);}}>
 <input ref={fileInput} type="file" accept="video/*,.mp4,.webm,.mov" hidden onChange={e=>{void importFile(e.target.files?.[0]);e.target.value='';}}/><input ref={projectInput} type="file" accept=".json" hidden onChange={e=>{void openProject(e.target.files?.[0]);e.target.value='';}}/>
 <video ref={video} src={videoUrl||undefined} preload="auto" playsInline className="source-video" onLoadedMetadata={()=>{sourceDuration.current=video.current?.duration||24;}} onError={()=>videoUrl&&inform('The recording could not be decoded. Import an H.264 MP4.')} />
 <header className="topbar"><a className="brand" href="/" aria-label="Take editor"><span className="brand-mark"><Film size={20}/></span>take<span className="brand-dot">.</span></a><div className="project-name"><span>Workspace /</span><input aria-label="Project name" value={p.name} maxLength={70} onChange={e=>update({name:e.target.value})}/></div><div className="header-actions"><span className="saved"><Check size={14}/>{saveStatus}</span><button className="btn" disabled={loading} onClick={()=>fileInput.current?.click()}>{loading?<Loader2 className="spin" size={15}/>:<Upload size={15}/>} Import video</button><button className="btn primary" onClick={()=>setExportOpen(true)}>Export video <ArrowUpRight size={16}/></button></div></header>
 <div className="editor-body"><Tabs value={tab} onValueChange={v=>setTab(String(v))} orientation="vertical" className="editor-tabs"><TabsList className="tool-rail">{[{Icon:Layers,label:'Canvas'},{Icon:ZoomIn,label:'Zoom'},{Icon:MousePointer2,label:'Cursor'},{Icon:Type,label:'Text'},{Icon:Scissors,label:'Clip'}].map(({Icon,label})=><TabsTrigger key={label} value={label} className="rail-item"><Icon size={20}/><span>{label}</span></TabsTrigger>)}<div className="rail-bottom"><button title="Save project file" aria-label="Save project file" onClick={()=>download(new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),`${p.name}.take.json`)}><Download size={19}/></button><button title="Open project file" aria-label="Open project file" onClick={()=>projectInput.current?.click()}><FolderOpen size={19}/></button></div></TabsList>
 <aside className="inspector"><div className="panel-heading"><h1>{tab}</h1><span className="tag">{tab==='Canvas'?'STYLE':'EDIT'}</span></div><TabsContent value="Canvas"><label>Aspect ratio</label><Choice label="Aspect ratio" value={p.ratio} options={[["16:9","▱  Landscape · 16:9"],["1:1","□  Square · 1:1"],["9:16","▯  Portrait · 9:16"]]} onChange={ratio=>update({ratio})}/><div className="section-heading">Background <span>Presets</span></div><div className="preset-grid">{themes.map((t,i)=><button title={t.name} aria-label={`${t.name} background`} aria-pressed={p.theme===i} key={t.name} style={{background:`linear-gradient(140deg,${t.colors.join(',')})`}} className={`preset ${p.theme===i?'selected':''}`} onClick={()=>update({theme:i})}>{p.theme===i&&<Check size={15}/>}</button>)}</div><div className="section-heading">Framing</div><Range label="Padding" value={p.padding} max={180} unit=" px" onChange={padding=>update({padding})}/><Range label="Corner radius" value={p.radius} max={60} unit=" px" onChange={radius=>update({radius})}/><Range label="Shadow" value={p.shadow} unit="%" onChange={shadow=>update({shadow})}/><div className="tip"><Sparkles size={17}/><p>A little space goes a long way.<br/><span>Give your product room to shine.</span></p></div></TabsContent>
 <TabsContent value="Zoom"><p className="panel-note">Guide attention to the moment that matters.</p><button className="btn wide" onClick={addZoom}><Plus size={14}/> Add zoom at playhead</button><div className="event-list">{p.zooms.map((z,i)=><button key={z.id} className={selected===z.id?'chosen':''} onClick={()=>{setSelected(z.id);seek(z.start+.7);setPlaying(false);}}><ZoomIn size={14}/><span>Zoom {i+1}</span><small>{formatTime(z.start)}</small></button>)}</div>{zoom?<><Range label="Magnification" value={zoom.scale} min={1} max={3} step={.05} unit="×" onChange={scale=>editZoom({scale})}/><Range label="Start" value={zoom.start} max={Math.max(0,total-.2)} step={.1} unit=" s" onChange={start=>editZoom({start,duration:Math.min(zoom.duration,total-start)})}/><Range label="Duration" value={zoom.duration} min={.2} max={Math.max(.2,total-zoom.start)} step={.1} unit=" s" onChange={duration=>editZoom({duration})}/><p className="panel-note">Click the preview to move the focus point. Smooth easing is applied automatically.</p><button className="btn danger wide" onClick={()=>{update({zooms:p.zooms.filter(z=>z.id!==selected)});setSelected('');}}><Trash2 size={14}/> Remove zoom</button></>:<p className="empty-note">Add a zoom or select one on the timeline.</p>}</TabsContent>
 <TabsContent value="Cursor"><p className="panel-note">The sample has a separate cursor you can customize.</p><div className="switch-row"><label htmlFor="cursor">Show sample cursor</label><Switch id="cursor" checked={p.cursor} disabled={!!videoUrl} onCheckedChange={cursor=>update({cursor})}/></div><Range label="Cursor size" value={p.cursorSize} min={12} max={60} unit=" px" onChange={cursorSize=>update({cursorSize})}/><div className="tip"><MousePointer2 size={17}/><p>{videoUrl?'Your video’s cursor is baked into the recording.':'Cursor styling applies to the sample.'}<br/><span>Imported videos keep their original cursor. Separate cursor capture comes with a future recorder.</span></p></div></TabsContent>
 <TabsContent value="Text"><p className="panel-note">A few words. A clearer story.</p><button className="btn wide" onClick={addText}><Plus size={14}/> Add callout</button><div className="event-list">{p.captions.map(c=><button key={c.id} className={selected===c.id?'chosen':''} onClick={()=>{setSelected(c.id);seek(c.start+.1);}}><Type size={14}/><span>{c.text.slice(0,22)}</span></button>)}</div>{caption?<><label htmlFor="callout">Callout text</label><textarea id="callout" maxLength={240} value={caption.text} onChange={e=>update({captions:p.captions.map(c=>c.id===selected?{...c,text:e.target.value}:c)})}/><Range label="Start" value={caption.start} max={Math.max(0,total-.2)} step={.1} unit=" s" onChange={start=>update({captions:p.captions.map(c=>c.id===selected?{...c,start,duration:Math.min(c.duration,total-start)}:c)})}/><Range label="Duration" value={caption.duration} min={.2} max={Math.max(.2,total-caption.start)} step={.1} unit=" s" onChange={duration=>update({captions:p.captions.map(c=>c.id===selected?{...c,duration}:c)})}/><button className="btn danger wide" onClick={()=>update({captions:p.captions.filter(c=>c.id!==selected)})}><Trash2 size={14}/> Remove callout</button></>:<p className="empty-note">Callouts appear in your preview and exported video.</p>}</TabsContent>
 <TabsContent value="Clip"><p className="panel-note">Select a clip on the timeline to trim it. Split and remove segments to cut pauses.</p><label>Playback speed</label><Choice label="Playback speed" value={String(p.speed)} options={[["0.5","0.5× · Slow"],["1","1× · Normal"],["1.5","1.5× · Brisk"],["2","2× · Fast"]]} onChange={v=>{update({speed:Number(v)});seek(0);}}/><div className="switch-row"><label htmlFor="audio">Include original audio</label><Switch id="audio" checked={!p.muted} onCheckedChange={v=>update({muted:!v})}/></div>{clip?<><Range label="Trim start" value={clip.start} max={Math.max(0,clip.end-.1)} step={.1} unit=" s" onChange={start=>{update({clips:p.clips.map(c=>c.id===clip.id?{...c,start}:c)});setPlaying(false);}}/><Range label="Trim end" value={clip.end} min={clip.start+.1} max={sourceDuration.current} step={.1} unit=" s" onChange={end=>{update({clips:p.clips.map(c=>c.id===clip.id?{...c,end}:c)});setPlaying(false);}}/><button className="btn danger wide" disabled={p.clips.length===1} onClick={()=>{update({clips:p.clips.filter(c=>c.id!==clip.id)});setSelectedClip(p.clips.find(c=>c.id!==clip.id)!.id);seek(0);}}><Trash2 size={14}/> Delete selected clip</button></>:<p className="empty-note">Select a video segment below.</p>}</TabsContent>
 </aside></Tabs>
 <section className="main-stage"><div className="stage-heading"><span><i/>{p.name||'Untitled demo'} {!videoUrl&&<span className="sample-badge">SAMPLE</span>}</span><span>PREVIEW <span className="separator">/</span> {W} × {H}</span></div><div className="preview-space"><canvas ref={canvas} width={W} height={H} className={`render-canvas ${tab==='Zoom'&&zoom?'focus-mode':''}`} style={{aspectRatio:p.ratio.replace(':','/'),maxHeight:p.ratio==='16:9'?'60vh':'53vh',width:p.ratio==='16:9'?'100%':'auto'}} aria-label="Video preview. In Zoom mode, click to position the camera focus." onClick={e=>{if(tab!=='Zoom'||!zoom)return;const r=e.currentTarget.getBoundingClientRect(),v=video.current;const sw=videoUrl&&v?v.videoWidth:1280,sh=videoUrl&&v?v.videoHeight:800,pad=p.padding/1080*Math.min(W,H),fit=Math.min((W-2*pad)/sw,(H-2*pad)/sh),fw=sw*fit,fh=sh*fit;editZoom({x:clamp(((e.clientX-r.left)/r.width*W-(W-fw)/2)/fw,0,1),y:clamp(((e.clientY-r.top)/r.height*H-(H-fh)/2)/fh,0,1)});seek(zoom.start+.7);}}/></div><div className="playback"><span>{formatTime(time)}<span className="muted"> / {formatTime(total)}</span></span><div><button aria-label="Go to start" onClick={()=>seek(0)}><SkipBack size={16}/></button><button className="play-button" aria-label={playing?'Pause':'Play'} title="Play / Pause (Space)" onClick={toggle}>{playing?<Pause size={18} fill="currentColor"/>:<Play size={18} fill="currentColor"/>}</button><button aria-label="Go to end" onClick={()=>{seek(total);setPlaying(false);}}><SkipForward size={16}/></button></div><div><button aria-label={p.muted?'Unmute':'Mute'} onClick={()=>update({muted:!p.muted})}>{p.muted?<VolumeX size={16}/>:<Volume2 size={16}/>}</button><span>Fit</span></div></div></section></div>
 <section className="timeline"><div className="timeline-toolbar"><div><button aria-label="Undo" title="Undo (Ctrl+Z)" disabled={!history.length} onClick={undo}><Undo2 size={16}/></button><button aria-label="Redo" title="Redo (Ctrl+Shift+Z)" disabled={!future.length} onClick={redo}><Redo2 size={16}/></button><span className="divider"/><button onClick={split}><Scissors size={16}/> Split</button></div><div><button className="btn" onClick={addZoom}><Plus size={14}/> Add zoom</button><button className="btn" onClick={addText}><Type size={14}/> Add text</button></div><span>{total.toFixed(1)} seconds</span></div><div className="tracks"><div className="track-labels"><span>Timeline</span><span><Film size={15}/> Video</span><span><ZoomIn size={15}/> Zoom</span>{p.captions.length>0&&<span><Type size={15}/> Text</span>}</div><div className="track-content"><div className="ruler" onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect();seek((e.clientX-r.left)/r.width*total);setPlaying(false);}} onPointerMove={e=>{if(e.buttons===1){const r=e.currentTarget.getBoundingClientRect();seek((e.clientX-r.left)/r.width*total);}}}>{Array.from({length:7},(_,i)=><span key={i}>{formatTime(total*i/6)}</span>)}</div><input className="timeline-scrubber" aria-label="Playhead position" type="range" min={0} max={total} step={.01} value={time} onChange={e=>{seek(Number(e.target.value));setPlaying(false);}}/><div className="clips-row">{p.clips.map((c,i)=><button key={c.id} className={`video-track ${selectedClip===c.id?'clip-selected':''}`} style={{flex:(c.end-c.start)}} title={`Select clip ${i+1}`} onClick={()=>{setSelectedClip(c.id);setTab('Clip');seek(p.clips.slice(0,i).reduce((s,c)=>s+c.end-c.start,0)/p.speed);}}>{Array.from({length:Math.max(2,Math.round((c.end-c.start)/(total*p.speed)*16))},(_,j)=><div key={j} className="mini-frame"><i/><i/><i/></div>)}<span>{fileName}{p.clips.length>1?` · ${i+1}`:''}</span></button>)}</div><div className="event-track">{p.zooms.map((z,i)=><button key={z.id} className={selected===z.id?'event-selected':''} style={{left:`${z.start/total*100}%`,width:`${Math.min(z.duration,total-z.start)/total*100}%`}} onClick={()=>{setSelected(z.id);setTab('Zoom');seek(z.start+.7);setPlaying(false);}}><ZoomIn size={12}/> Zoom {i+1} <span>{z.scale.toFixed(1)}×</span></button>)}</div>{p.captions.length>0&&<div className="event-track text-track">{p.captions.map(c=><button key={c.id} style={{left:`${c.start/total*100}%`,width:`${Math.min(c.duration,total-c.start)/total*100}%`}} onClick={()=>{setSelected(c.id);setTab('Text');seek(c.start+.1);}}><Type size={12}/>{c.text}</button>)}</div>}<div className="playhead" style={{left:`${time/total*100}%`}}/></div></div></section>
 <footer className="statusbar"><span><span className="status-dot"/> Everything stays on your device</span><span>Made for your next big little launch <Sparkles size={12}/></span></footer>
 {notice&&<div className="toast-message" role="status"><Check size={15}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}{dragging&&<div className="drop-overlay"><Upload size={38}/><h2>Drop your recording here</h2><p>MP4, WebM, or MOV</p></div>}
 <Dialog open={exportOpen} onOpenChange={v=>{if(!exporting)setExportOpen(v);}}><DialogContent className="export-dialog" showCloseButton={!exporting}><DialogTitle>Ready for your close-up.</DialogTitle><DialogDescription>Export your edit with backgrounds, zooms, and callouts included.</DialogDescription><div className="export-summary"><Film size={26}/><div><b>{p.name}</b><span>{formatTime(total)} · {p.ratio} · 30 fps</span></div></div><label>Resolution</label><Choice label="Export resolution" value={quality} options={[["720","720p · Smaller file"],["1080","1080p · High quality"]]} onChange={setQuality}/><p className="panel-note">MP4 when your browser supports it; WebM otherwise. Export runs in real time. Keep this tab visible until it finishes.</p>{exporting?<><Progress aria-label="Export progress" value={progress}/><div className="export-progress"><span>Rendering your demo… {Math.round(progress)}%</span><button onClick={()=>{cancel.current=true;}}>Cancel</button></div></>:<button className="btn primary wide" onClick={()=>void exportVideo()}><Download size={16}/> Export & download</button>}</DialogContent></Dialog>
 </main>;
}
